---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install pre-commit
        run: |
          pip install --upgrade pip
          pip install --upgrade pre-commit
      - name: Cache pre-commit hooks
        id: cache-pre-commit-hooks
        uses: actions/cache@v5
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}-${{ env.CACHE_NUMBER }} # yamllint disable-line rule:line-length
      - name: Install pre-commit hooks
        if: steps.cache-pre-commit-hooks.outputs.cache-hit != 'true'
        run: |
          pre-commit install-hooks
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

  test-unit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      coverage: ${{ steps.coverage-unit.outputs.coverage }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Git
        run: |
          git config --global user.name 'Test User'
          git config --global user.email 'test@example.com'
      - name: Run unit tests with coverage
        id: coverage-unit
        if: matrix.os == 'ubuntu-latest'
        run: |
          .github/scripts/run-kcov.sh unit tests/test-runner.sh
      - name: Run unit tests without coverage
        if: matrix.os != 'ubuntu-latest'
        run: bash tests/test-runner.sh

  test-integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      coverage: ${{ steps.coverage-integration.outputs.coverage }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Git
        run: |
          git config --global user.name 'Test User'
          git config --global user.email 'test@example.com'
      - name: Install pre-commit
        run: |
          pip install --upgrade pip
          pip install pre-commit
      - name: Run integration tests with coverage
        id: coverage-integration
        if: matrix.os == 'ubuntu-latest'
        run: |
          .github/scripts/run-kcov.sh integration tests/test-integration.sh
      - name: Run integration tests without coverage
        if: matrix.os != 'ubuntu-latest'
        run: bash tests/test-integration.sh

  merge-coverage-reports:
    runs-on: ubuntu-latest
    needs: [test-unit, test-integration]
    steps:
      - name: Merge coverage reports
        run: |
          mkdir -p unit integration
          echo ${{ needs.test-unit.outputs.coverage }} >> unit/coverage.json
          echo ${{ needs.test-integration.outputs.coverage }} >> integration/coverage.json
          kcov --merge coverage-merged unit integration
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: coverage-merged
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
